#!/bin/sh
#
# $FreeBSD: ports/sysutils/moosefs-chunkserver/files/mfschunkserver.in,v 1.2 2012/01/14 08:57:02 dougb Exp $
#

# PROVIDE: mfschunkserver
# REQUIRE: LOGIN 
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf or or /etc/rc.conf to enable mfschunkserver:
#
# mfschunkserver_enable="YES"
#

. /etc/rc.subr

name=mfschunkserver
rcvar=mfschunkserver_enable

command=/usr/local/sbin/${name}

stop_postcmd=stop_postcmd
start_precmd=start_precmd

stop_postcmd()
{
  rm -f $pidfile
}

start_precmd() 
{

	mkdir -p /var/mfs
	chown -R mfs:mfs /var/mfs
}

# set defaults
mfschunkserver_enable=${mfschunkserver_enable:-"NO"}
mfschunkserver_flags=${mfschunkserver_flags:-"-c /usr/local/etc/mfschunkserver.cfg"}

load_rc_config $name
run_rc_command "$1"
